from source_code.errors.block_error import BlockError


class NoOutputBlockError(BlockError):
    pass
